### ISSUE TITLE
Some updated examples?

### ISSUE THREAD

**Issue by jatoledo** [EIS-Bonn/Squerall#9]
Hi, 
Could you add some examples to run the tool?
I have some problems to run this tool and I can see the links in the docker are old.
 central maven doesn't exist, now is: https://repo.maven.apache.org/

Thank you.

**Comment by mnmami** [comment]
Hi @jatoledo,

I'd like to help you with your problems, indeed. Please open (Github) issues with specific errors so I can have a look. Thanks.

**Comment by jatoledo** [comment]
Ok,I close this issue.
